In [11]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from typing import List

import time

import pickle

from statistics import mean

from xgboost import XGBClassifier

from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import silhouette_score

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split

from sklearn.neural_network import MLPClassifier

In [3]:
df = pd.read_pickle('../../data/processed/train.pkl')
df

target    var_0   var_1    var_2   var_3    var_4    var_5  \
ID_code                                                                    
train_0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834   
train_1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433   
train_2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837   
train_3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361   
train_4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486   
...              ...      ...     ...      ...     ...      ...      ...   
train_199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081   
train_199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628   
train_199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086   
train_199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339   
train_199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488   

               var_6    var_7   var_8  ...  var_190  var_191  var_192  \
ID_code                                ...                              
train_0       5.1187  18.6266 -4.9200  ...   4.4354   3.9642   3.1364   
train_1       5.6208  16.5338  3.1468  ...   7.6421   7.7214   2.5837   
train_2       6.9427  14.6155 -4.9193  ...   2.9057   9.7905   1.6704   
train_3       5.8428  14.9250 -5.8609  ...   4.4666   4.7433   0.7178   
train_4       5.9405  19.2514  6.2654  ...  -1.4905   9.5214  -0.1508   
...              ...      ...     ...  ...      ...      ...      ...   
train_199995  5.6709  15.1516 -0.6209  ...   6.1415  13.2305   3.9901   
train_199996  5.8802  21.5940 -3.6797  ...   4.9611   4.6549   0.6998   
train_199997  4.5555  21.5571  0.1202  ...   4.0651   5.4414   3.1032   
train_199998  6.0479  17.0152 -2.1926  ...   2.6840   8.6587   2.7337   
train_199999  5.2839  15.2058 -0.4541  ...   8.9842   1.6893   0.1276   

              var_193    var_194  var_195  var_196  var_197    var_198  \
ID_code                                                                  
train_0        1.6910  18.522699  -2.3978   7.8784   8.5635  12.780300   
train_1       10.9516  15.430500   2.0339   8.1267   8.7889  18.356001   
train_2        1.6858  21.604200   3.1417  -6.5213   8.2675  14.722200   
train_3        1.4214  23.034700  -1.2706  -2.9275  10.2922  17.969700   
train_4        9.1942  13.287600  -1.5121   3.9267   9.5031  17.997400   
...               ...        ...      ...      ...      ...        ...   
train_199995   0.9388  18.024900  -1.7939   2.1661   8.5326  16.666000   
train_199996   1.8341  22.271700   1.7337  -2.1651   6.7419  15.905400   
train_199997   4.8793  23.531099  -1.5736   1.2832   8.7155  13.832900   
train_199998  11.1178  20.415800  -0.0786   6.7980  10.0342  15.528900   
train_199999   0.3766  15.210100  -2.4907  -2.2342   8.1857  12.128400   

              var_199  
ID_code                
train_0       -1.0914  
train_1        1.9518  
train_2        0.3965  
train_3       -8.9996  
train_4       -8.8104  
...               ...  
train_199995 -17.8661  
train_199996   0.3388  
train_199997   4.1995  
train_199998 -13.9001  
train_199999   0.1385  

[200000 rows x 201 columns]

In [4]:
X=df.drop("target", axis=1)
y=df["target"]

In [5]:
skf = StratifiedKFold(n_splits=7,shuffle=False)
skf.get_n_splits(X, y)

7

In [6]:
#Genero lista de resultados
results=[]
lista_name=[]
tiempo_ejecucion=[]

In [9]:
MLP0 = MLPClassifier()

In [10]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]
for train_index, test_index in skf.split(X, y):
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    MLP0.fit(X_train, y_train)
    y_pred=np.asarray(MLP0.predict(X_test))
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))
print("El valor promedio del recall es", mean(recall_prom))
lista_name.append("Fulldata_MLP0Classifier")
fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[24915   785]
 [ 1987   885]] 0.5299401197604791 0.3081476323119777


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


El valor promedio del recall es 0.279578636232656
el tiempo fue de  2456.112848997116


In [7]:
MLP = MLPClassifier(max_iter=2000,hidden_layer_sizes=(100,75))

In [8]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]

for train_index, test_index in skf.split(X, y):
    
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    
    MLP.fit(X_train, y_train)
    
    y_pred=np.asarray(MLP.predict(X_test))
    
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))

print("El valor promedio del recall es", mean(recall_prom))

lista_name.append("Fulldata_MLPClassifier")

fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[24784   916]
 [ 2017   855]] 0.4827780914737436 0.29770194986072424
El valor promedio del recall es 0.2985372094367388
el tiempo fue de  4284.473002910614


In [9]:
MLP2 = MLPClassifier(max_iter=2000,hidden_layer_sizes=(100,125))

In [10]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]

for train_index, test_index in skf.split(X, y):
    
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    
    MLP2.fit(X_train, y_train)
    
    y_pred=np.asarray(MLP2.predict(X_test))
    
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))

print("El valor promedio del recall es", mean(recall_prom))

lista_name.append("Fulldata_MLP2Classifier")

fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[24930   770]
 [ 2074   798]] 0.5089285714285714 0.27785515320334264
El valor promedio del recall es 0.28196855972766066
el tiempo fue de  4438.673186540604


In [11]:
MLP3 = MLPClassifier(max_iter=2000,hidden_layer_sizes=(100,200))

In [12]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]

for train_index, test_index in skf.split(X, y):
    
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    
    MLP3.fit(X_train, y_train)
    
    y_pred=np.asarray(MLP3.predict(X_test))
    
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))

print("El valor promedio del recall es", mean(recall_prom))

lista_name.append("Fulldata_MLP3Classifier")

fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[24591  1109]
 [ 2091   781]] 0.4132275132275132 0.2719359331476323
El valor promedio del recall es 0.29420948719046885
el tiempo fue de  6649.716140508652


In [13]:
MLP4 = MLPClassifier(max_iter=2000,hidden_layer_sizes=(200,250))

In [14]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]

for train_index, test_index in skf.split(X, y):
    
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    
    MLP4.fit(X_train, y_train)
    
    y_pred=np.asarray(MLP4.predict(X_test))
    
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))

print("El valor promedio del recall es", mean(recall_prom))

lista_name.append("Fulldata_MLP4Classifier")

fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[24213  1487]
 [ 2013   859]] 0.36615515771526 0.29909470752089135
El valor promedio del recall es 0.3118724638151206
el tiempo fue de  9516.40111207962


In [15]:
MLP5 = MLPClassifier(max_iter=2000,hidden_layer_sizes=(300,250))

In [16]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]
for train_index, test_index in skf.split(X, y):
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    MLP5.fit(X_train, y_train)
    y_pred=np.asarray(MLP5.predict(X_test))
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))
print("El valor promedio del recall es", mean(recall_prom))
lista_name.append("Fulldata_MLP5Classifier")
fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[24089  1611]
 [ 1923   949]] 0.370703125 0.3304317548746518
El valor promedio del recall es 0.32610188427352965
el tiempo fue de  9665.995199680328


In [17]:
MLP6 = MLPClassifier(max_iter=2000,hidden_layer_sizes=(300,50))


In [18]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]
for train_index, test_index in skf.split(X, y):
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    MLP6.fit(X_train, y_train)
    y_pred=np.asarray(MLP6.predict(X_test))
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))
print("El valor promedio del recall es", mean(recall_prom))
lista_name.append("Fulldata_MLP6Classifier")
fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[23948  1752]
 [ 1848  1024]] 0.3688760806916426 0.3565459610027855
El valor promedio del recall es 0.35217412818027555
el tiempo fue de  9657.28878235817


In [7]:
MLP7 = MLPClassifier(max_iter=2000,hidden_layer_sizes=(300,300,300))


In [8]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]
for train_index, test_index in skf.split(X, y):
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    MLP7.fit(X_train, y_train)
    y_pred=np.asarray(MLP7.predict(X_test))
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))
print("El valor promedio del recall es", mean(recall_prom))
lista_name.append("Fulldata_MLP7Classifier")
fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[24231  1469]
 [ 1942   930]] 0.3876615256356815 0.32381615598885793
El valor promedio del recall es 0.32485824669572627
el tiempo fue de  17199.50600361824


In [7]:
MLP8 = MLPClassifier(max_iter=2000,hidden_layer_sizes=(300,50,50))


In [8]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]
for train_index, test_index in skf.split(X, y):
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    MLP8.fit(X_train, y_train)
    y_pred=np.asarray(MLP8.predict(X_test))
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))
print("El valor promedio del recall es", mean(recall_prom))
lista_name.append("Fulldata_MLP8Classifier")
fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)


#MLP con recall mas alto

[[23965  1735]
 [ 1852  1020]] 0.3702359346642468 0.3551532033426184
El valor promedio del recall es 0.3326687986663013
el tiempo fue de  10317.366469860077


In [12]:
pkl_file = "../../models/best_MLP.pkl"

with open(pkl_file, 'wb') as file:
    pickle.dump(MLP8, file)

In [13]:
MLP9 = MLPClassifier(max_iter=2000,hidden_layer_sizes=(300,200,100))


In [14]:
#==================================MLPClassifier================================================
contador=0
inicio=time.time()
recall_prom=[]
for train_index, test_index in skf.split(X, y):
    X_train=X.iloc[train_index]
    X_test=X.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    MLP9.fit(X_train, y_train)
    y_pred=np.asarray(MLP9.predict(X_test))
    cm=confusion_matrix(y_test, y_pred)
    precision = precision_score(y_test, y_pred,average='binary')    
    recall = recall_score(y_test, y_pred,average='binary')
    recall_prom.append(recall)
    if contador==2:
        print(cm,precision,recall)
    contador+=1
    
results.append(mean(recall_prom))
print("El valor promedio del recall es", mean(recall_prom))
lista_name.append("Fulldata_MLP9Classifier")
fin = time.time()
tiempo_ejecucion.append(fin-inicio)
print("el tiempo fue de ", fin-inicio)

[[24382  1318]
 [ 2002   870]] 0.3976234003656307 0.30292479108635095
El valor promedio del recall es 0.3383936445842122
el tiempo fue de  13079.705614328384
